language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk11
env:
  matrix:
    - PROFILES=javac
    - PROFILES=jdt
    - PROFILES=javac,el3
    - PROFILES=jdt,el3
    
script: "mvn clean install -P ${PROFILES}"
