language: java
cache:
  directories:
  - $HOME/.m2
jdk:
  - openjdk8
  - openjdk11
  - openjdk13
  - openjdk14
env:
  - PROFILES=javac
  - PROFILES=jdt
  - PROFILES=javac,java11
  - PROFILES=jdt,java11

matrix:
  exclude:

    - jdk: openjdk8
      env: PROFILES=javac,java11
    - jdk: openjdk8
      env: PROFILES=jdt,java11
install: "mvn help:active-profiles help:effective-pom help:effective-settings -q -P ${PROFILES},-standard-with-extra-repos"
script: "mvn clean install -U  -P ${PROFILES},-standard-with-extra-repos -Dmaven.javadoc.skip=true"
